### ISSUE TITLE
Improved syntax highlighting

### ISSUE THREAD

**Issue by eedahl** [yu961549745/VSCodeHighlightForMaple#3]
It appears the syntax highlighting doesn't work for library specific things like DifferentialGeometry specific functions. More syntax highlighting options like for operators and lists would be nice.

**Comment by yu961549745** [comment]
The only problem of fix the highlighting problem is getting the complete function list of Maple.
Maybe it is hard to do that, because there are so many packages and functions.
But, make a customiztion is easy. Just modify the line 65 in the [https://github.com/yu961549745/VSCodeHighlightForMaple/blob/master/syntaxes/maple.json](maple.json), you can add the functions you want.

By the way, it is easy to hignlighting the operators, but I don't think it looks good.

**Comment by eedahl** [comment]
You're right, that seems hard without getting the data directly from Maple maybe. The closest thing is the list of all functions in the overview sections in the help files. Thanks for telling me how, I'll at least add these to mine :)
https://www.maplesoft.com/support/help/Maple/view.aspx?path=DifferentialGeometry
https://www.maplesoft.com/support/help/Maple/view.aspx?path=DifferentialGeometry/Tensor

**Comment by yu961549745** [comment]
You're welcome.
By the way, the local folder of this extension is  `C:\Users\<YOUR_USER_NAME>\.vscode\extensions\yjt.maple-1.2.7`.
